name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch any Git submodules (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Step 2: Setup Hugo with a specific version
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.97.3'  # Specify the desired version
          extended: true          # Enable the extended version for SCSS processing

      # Step 3: Build the Hugo site
      - name: Build
        run: hugo --minify

      # Step 4: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # Ensure deployment happens only on the main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./public
