name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to the main branch
  pull_request:  # Optional: Build on pull requests for testing

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Git submodules if applicable
          fetch-depth: 0    # Fetch full history for .GitInfo and .Lastmod

      # Step 2: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # Use the latest Hugo version
          extended: true          # Enable Hugo extended version for SCSS processing

      # Step 3: Update Hugo Modules
      - name: Update Hugo Modules
        run: |
          hugo mod get -u ./...
          hugo mod tidy
          hugo mod clean

      # Step 4: Build the Hugo site
      - name: Build Hugo Site
        run: hugo --minify

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Directory to publish to GitHub Pages
